# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9a3827bf2f0399be6a0a254bd31dff552e016c15e014eea13cf3cf9a6e3f759abfd517e7e8f67967e10cafd51cad72c73a79ee1e9e95e12e2d47863d63a8a2

test:
  secret_key_base: 5b895628eedb87d071b3cf670571b10f7f1f63ba55d75d31d7645ac2afae4fc4f1424eac1dfeefdf713fbdf4ef80e1fcead060b529228b3f3dde9fe4e4e2d414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
